const transEls=[...document.querySelectorAll('[data-en][data-zh]')];
function preferredLanguage(){const urlLang=new URLSearchParams(location.search).get('lang');if(urlLang==='en'||urlLang==='zh')return urlLang;let saved=null;try{saved=localStorage.getItem('exai-lang')}catch(e){}if(saved==='en'||saved==='zh')return saved;const nav=(navigator.language||'en').toLowerCase();return /^(zh|yue)/.test(nav)?'zh':'en'}
function setLanguage(lang){document.documentElement.lang=lang==='zh'?'zh-Hant':'en';transEls.forEach(el=>{el.textContent=el.dataset[lang]});document.getElementById('enBtn').classList.toggle('active',lang==='en');document.getElementById('zhBtn').classList.toggle('active',lang==='zh');try{localStorage.setItem('exai-lang',lang)}catch(e){}renderQuestion();if(lastFeedbackCorrect!==null&&fp&&fp.classList.contains('show')){refreshFeedbackLanguage(lastFeedbackCorrect);const q=questionSets[mode],btns=[...ans.querySelectorAll('button')];if(btns[q.correct])btns[q.correct].classList.add('correct');}const activeScope=document.querySelector('#schoolTree button.active');if(activeScope&&typeof setScope==='function')setScope(activeScope.dataset.scope,activeScope);}
let currentLang=preferredLanguage();document.getElementById('enBtn').addEventListener('click',()=>{currentLang='en';setLanguage('en')});document.getElementById('zhBtn').addEventListener('click',()=>{currentLang='zh';setLanguage('zh')});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('on')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
const questionSets={
english:{skill:{en:'Grammar · Subject–Verb Agreement',zh:'英文文法 · 主謂一致'},text:{en:'Choose the correct word to complete the sentence.',zh:'選出最適合填入空格的答案。'},visual:`<div class="grammar-visual"><div class="giant">Neither the students<br>nor the <em>teacher</em> ___ aware.</div><div class="grammar-rule"><b>${currentLang==='zh'?'思考提示':'Thinking hint'}</b><div>${currentLang==='zh'?'在 neither…nor 結構中，動詞通常與最接近它的主語保持一致。':'With “neither…nor”, agreement usually follows the subject closest to the verb.'}</div></div></div>`,answers:['were','was','have been','are'],correct:1,reason:{en:'With <b>neither…nor</b>, the verb agrees with the subject nearest to it. The nearest subject is <b>teacher</b>, which is singular, so <b>was</b> is correct.',zh:'在 <b>neither…nor</b> 結構中，動詞通常與最接近它的主語一致。最接近動詞的是單數名詞 <b>teacher</b>，因此應使用 <b>was</b>。'},tip:{en:'Locate the noun closest to the verb before deciding singular or plural agreement.',zh:'先找出最接近動詞的名詞，再判斷動詞應使用單數還是複數形式。'},mastery:'Grammar · 79 → 80'},
math:{skill:{en:'Math · Linear Graphs',zh:'數學 · 直線圖'},text:{en:'The line passes through (1, 3) and (3, 7). What is its gradient?',zh:'直線通過 (1, 3) 和 (3, 7)。它的斜率是多少？'},visual:`<div class="graphbox"><svg viewBox="0 0 520 320" role="img" aria-label="Coordinate graph with line through the labelled points one comma three and three comma seven"><g class="gridline"><line x1="90" y1="30" x2="90" y2="245"/><line x1="150" y1="30" x2="150" y2="245"/><line x1="210" y1="30" x2="210" y2="245"/><line x1="270" y1="30" x2="270" y2="245"/><line x1="330" y1="30" x2="330" y2="245"/><line x1="390" y1="30" x2="390" y2="245"/><line x1="450" y1="30" x2="450" y2="245"/><line x1="60" y1="42" x2="485" y2="42"/><line x1="60" y1="87" x2="485" y2="87"/><line x1="60" y1="132" x2="485" y2="132"/><line x1="60" y1="177" x2="485" y2="177"/><line x1="60" y1="222" x2="485" y2="222"/></g><line class="axis" x1="60" y1="245" x2="490" y2="245"/><line class="axis" x1="90" y1="270" x2="90" y2="22"/><polyline class="mathline" points="90,222 150,177 210,132 270,87 330,42"/><circle class="point" cx="150" cy="177" r="7"/><circle class="point" cx="270" cy="87" r="7"/><text class="label" x="184" y="205">(1, 3)</text><text class="label" x="306" y="99">(3, 7)</text><text class="tick" x="150" y="261" text-anchor="middle">1</text><text class="tick" x="210" y="261" text-anchor="middle">2</text><text class="tick" x="270" y="261" text-anchor="middle">3</text><text class="tick" x="330" y="261" text-anchor="middle">4</text><text class="tick" x="390" y="261" text-anchor="middle">5</text><text class="tick" x="78" y="225" text-anchor="end">1</text><text class="tick" x="78" y="180" text-anchor="end">3</text><text class="tick" x="78" y="135" text-anchor="end">5</text><text class="tick" x="78" y="90" text-anchor="end">7</text><text class="tick" x="78" y="45" text-anchor="end">9</text><text class="label" x="494" y="261">x</text><text class="label" x="72" y="24">y</text></svg></div>`,answers:['1','2','3','4'],correct:1,reason:{en:'Using the two labelled points, the rise is <b>7 − 3 = 4</b> and the run is <b>3 − 1 = 2</b>. The gradient is therefore <b>4 ÷ 2 = 2</b>.',zh:'利用圖中兩個已標示的點，縱向變化為 <b>7 − 3 = 4</b>，橫向變化為 <b>3 − 1 = 2</b>，所以斜率為 <b>4 ÷ 2 = 2</b>。'},tip:{en:'Choose two clear points on the line, then calculate rise ÷ run.',zh:'先選取直線上兩個清楚的點，再計算「縱向變化 ÷ 橫向變化」。'},mastery:'Linear Graphs · 81 → 82'}};
let mode=Math.random()<.5?'english':'math',attempt=0,locked=false,lastFeedbackCorrect=null;
const qv=document.getElementById('questionVisual'),qt=document.getElementById('questionText'),ans=document.getElementById('answers'),tag=document.getElementById('skillTag'),fp=document.getElementById('feedbackPanel'),note=document.getElementById('attemptNote'),ai=document.getElementById('aiWork'),trans=document.getElementById('teacherTransition');
function renderQuestion(){if(!qv)return;const q=questionSets[mode];q.visual=mode==='english'?`<div class="grammar-visual"><div class="giant">Neither the students<br>nor the <em>teacher</em> ___ aware.</div><div class="grammar-rule"><b>${currentLang==='zh'?'思考提示':'Thinking hint'}</b><div>${currentLang==='zh'?'在 neither…nor 結構中，動詞通常與最接近它的主語保持一致。':'With “neither…nor”, agreement usually follows the subject closest to the verb.'}</div></div></div>`:q.visual;qv.innerHTML=q.visual;tag.textContent=q.skill[currentLang];qt.textContent=q.text[currentLang];ans.innerHTML='';q.answers.forEach((a,i)=>{const b=document.createElement('button');b.type='button';b.textContent=String.fromCharCode(65+i)+' · '+a;b.addEventListener('click',()=>answer(i,b));ans.appendChild(b)});document.getElementById('englishSwitch').classList.toggle('active',mode==='english');document.getElementById('mathSwitch').classList.toggle('active',mode==='math');note.textContent=currentLang==='zh'?'選擇答案後即會提交；如答錯，可再試一次。':'Choose an answer to submit. If it’s incorrect, you can try once more.'}
function reset(m){mode=m;attempt=0;locked=false;lastFeedbackCorrect=null;fp.classList.remove('show');ai.classList.remove('show');ai.querySelectorAll('.ai-step').forEach(x=>x.classList.remove('done'));trans.classList.remove('show');renderQuestion()}
function answer(i,b){if(locked)return;const q=questionSets[mode],buttons=[...ans.querySelectorAll('button')];if(i===q.correct){locked=true;b.classList.add('correct');showFeedback(true)}else{b.classList.add('wrong');attempt++;if(attempt<2){b.disabled=true;note.textContent=currentLang==='zh'?'還差一點。再試一次，留意最關鍵的規則。':'Not quite. Try once more — focus on the key rule.'}else{locked=true;buttons[q.correct].classList.add('correct');showFeedback(false)}}}
function refreshFeedbackLanguage(correct){
  const q=questionSets[mode];
  document.getElementById('resultState').textContent=correct?(currentLang==='zh'?'✓ 正確 — 掌握度 +1':'✓ Correct — +1 mastery'):(currentLang==='zh'?'一起看看正確的解題思路':'Let’s work through the correct reasoning');
  document.getElementById('resultState').className='resultstate '+(correct?'good':'bad');
  document.getElementById('reasonText').innerHTML=q.reason[currentLang];
  document.getElementById('tipText').textContent=q.tip[currentLang];
  const masteryMap={english:{en:'Grammar · 79 → 80',zh:'文法 · 79 → 80'},math:{en:'Linear Graphs · 81 → 82',zh:'直線圖 · 81 → 82'}};
  document.getElementById('masterySkill').textContent=masteryMap[mode][currentLang];
  document.querySelectorAll('.barrow').forEach((r,idx)=>r.classList.toggle('correct-choice',idx===q.correct));
}
function showFeedback(correct){
  lastFeedbackCorrect=correct;
  refreshFeedbackLanguage(correct);
  fp.classList.add('show');
  setTimeout(()=>{ai.classList.add('show');const steps=[...ai.querySelectorAll('.ai-step')];steps.forEach((el,n)=>setTimeout(()=>el.classList.add('done'),220+n*260))},420);
  setTimeout(()=>trans.classList.add('show'),1900)
}
document.getElementById('englishSwitch').addEventListener('click',()=>reset('english'));document.getElementById('mathSwitch').addEventListener('click',()=>reset('math'));
const scopes={
school:{label:{en:'Whole School',zh:'全校'},completion:'84%',active:'354',attention:'18',change:'+6%',trend:'up',line:[170,158,164,145,151,128,136],gap:'Grammar',gapScore:72,heat:[['Grade 1',84,72,81,85],['Grade 2',89,84,86,90],['Grade 3',86,82,84,88],['Grade 4',83,76,82,85],['Grade 5',85,80,83,86],['Grade 6',88,84,85,89]],title:{en:'School learning completion · Jan–Jul',zh:'全校學習完成率 · 1月至7月'}},
g1:{label:{en:'Grade 1',zh:'一年級'},completion:'81%',active:'60',attention:'7',change:'+3%',trend:'mixed',line:[176,163,171,154,160,143,151],gap:'Grammar',gapScore:68,heat:[['Class 1A',88,82,86,90],['Class 1B',73,58,69,70],['Class 1C',86,79,84,88]],title:{en:'Grade 1 completion · Jan–Jul',zh:'一年級完成率 · 1月至7月'}},
'1a':{label:{en:'Class 1A',zh:'1A 班'},completion:'90%',active:'20',attention:'1',change:'+8%',trend:'up',line:[169,153,158,136,142,111,120],gap:'Grammar',gapScore:82,heat:[['Reading',92],['Grammar',82],['Vocabulary',88],['Listening',91]],title:{en:'Class 1A completion · Jan–Jul',zh:'1A 班完成率 · 1月至7月'}},
'1b':{label:{en:'Class 1B',zh:'1B 班'},completion:'66%',active:'20',attention:'5',change:'−7%',trend:'down',line:[148,155,151,166,160,177,188],gap:'Grammar',gapScore:58,heat:[['Reading',73],['Grammar',58],['Vocabulary',69],['Listening',70]],title:{en:'Class 1B completion · Jan–Jul',zh:'1B 班完成率 · 1月至7月'}},
'1c':{label:{en:'Class 1C',zh:'1C 班'},completion:'87%',active:'20',attention:'1',change:'+5%',trend:'up',line:[172,161,165,149,139,145,125],gap:'Grammar',gapScore:79,heat:[['Reading',86],['Grammar',79],['Vocabulary',84],['Listening',88]],title:{en:'Class 1C completion · Jan–Jul',zh:'1C 班完成率 · 1月至7月'}},
g2:{label:{en:'Grade 2',zh:'二年級'},completion:'88%',active:'60',attention:'2',change:'+5%',trend:'up',line:[174,162,168,148,139,145,116],gap:'Vocabulary',gapScore:80,heat:[['Class 2A',92,87,89,94],['Class 2B',88,83,81,90],['Class 2C',87,84,80,88]],title:{en:'Grade 2 completion · Jan–Jul',zh:'二年級完成率 · 1月至7月'}},
'2a':{label:{en:'Class 2A',zh:'2A 班'},completion:'91%',active:'20',attention:'0',change:'+7%',trend:'up',line:[170,159,164,143,149,117,108],gap:'Grammar',gapScore:87,heat:[['Reading',94],['Grammar',87],['Vocabulary',89],['Listening',94]],title:{en:'Class 2A completion · Jan–Jul',zh:'2A 班完成率 · 1月至7月'}},
'2b':{label:{en:'Class 2B',zh:'2B 班'},completion:'86%',active:'20',attention:'1',change:'+2%',trend:'mixed',line:[161,166,154,158,146,150,132],gap:'Vocabulary',gapScore:81,heat:[['Reading',88],['Grammar',83],['Vocabulary',81],['Listening',90]],title:{en:'Class 2B completion · Jan–Jul',zh:'2B 班完成率 · 1月至7月'}},
'2c':{label:{en:'Class 2C',zh:'2C 班'},completion:'87%',active:'20',attention:'1',change:'+4%',trend:'up',line:[173,160,164,151,138,142,125],gap:'Vocabulary',gapScore:80,heat:[['Reading',87],['Grammar',84],['Vocabulary',80],['Listening',88]],title:{en:'Class 2C completion · Jan–Jul',zh:'2C 班完成率 · 1月至7月'}},
g3:{label:{en:'Grade 3',zh:'三年級'},completion:'85%',active:'60',attention:'3',change:'−1%',trend:'mixed',line:[143,149,138,146,140,153,148],gap:'Grammar',gapScore:76,heat:[['Class 3A',90,84,86,91],['Class 3B',81,69,79,82],['Class 3C',87,76,84,88]],title:{en:'Grade 3 completion · Jan–Jul',zh:'三年級完成率 · 1月至7月'}},
'3a':{label:{en:'Class 3A',zh:'3A 班'},completion:'88%',active:'20',attention:'1',change:'+3%',trend:'up',line:[158,149,153,138,143,128,120],gap:'Grammar',gapScore:84,heat:[['Reading',90],['Grammar',84],['Vocabulary',86],['Listening',91]],title:{en:'Class 3A completion · Jan–Jul',zh:'3A 班完成率 · 1月至7月'}},
'3b':{label:{en:'Class 3B',zh:'3B 班'},completion:'82%',active:'20',attention:'2',change:'−4%',trend:'down',line:[139,143,151,146,157,162,169],gap:'Grammar',gapScore:69,heat:[['Reading',81],['Grammar',69],['Vocabulary',79],['Listening',82]],title:{en:'Class 3B completion · Jan–Jul',zh:'3B 班完成率 · 1月至7月'}},
'3c':{label:{en:'Class 3C',zh:'3C 班'},completion:'85%',active:'20',attention:'0',change:'+1%',trend:'mixed',line:[152,147,154,145,149,141,137],gap:'Grammar',gapScore:76,heat:[['Reading',87],['Grammar',76],['Vocabulary',84],['Listening',88]],title:{en:'Class 3C completion · Jan–Jul',zh:'3C 班完成率 · 1月至7月'}},
g4:{label:{en:'Grade 4',zh:'四年級'},completion:'82%',active:'58',attention:'3',change:'−3%',trend:'down',line:[145,150,147,158,154,169,174],gap:'Grammar',gapScore:70,heat:[['Class 4A',87,79,84,89],['Class 4B',78,62,76,80]],title:{en:'Grade 4 completion · Jan–Jul',zh:'四年級完成率 · 1月至7月'}},
'4a':{label:{en:'Class 4A',zh:'4A 班'},completion:'85%',active:'29',attention:'1',change:'+1%',trend:'mixed',line:[151,147,155,145,150,141,136],gap:'Grammar',gapScore:79,heat:[['Reading',87],['Grammar',79],['Vocabulary',84],['Listening',89]],title:{en:'Class 4A completion · Jan–Jul',zh:'4A 班完成率 · 1月至7月'}},
'4b':{label:{en:'Class 4B',zh:'4B 班'},completion:'79%',active:'29',attention:'2',change:'−6%',trend:'down',line:[138,146,143,157,164,168,181],gap:'Grammar',gapScore:62,heat:[['Reading',78],['Grammar',62],['Vocabulary',76],['Listening',80]],title:{en:'Class 4B completion · Jan–Jul',zh:'4B 班完成率 · 1月至7月'}},
g5:{label:{en:'Grade 5',zh:'五年級'},completion:'83%',active:'58',attention:'2',change:'+2%',trend:'mixed',line:[158,149,154,145,151,139,134],gap:'Vocabulary',gapScore:74,heat:[['Class 5A',88,82,83,89],['Class 5B',81,74,65,82]],title:{en:'Grade 5 completion · Jan–Jul',zh:'五年級完成率 · 1月至7月'}},
'5a':{label:{en:'Class 5A',zh:'5A 班'},completion:'86%',active:'29',attention:'1',change:'+4%',trend:'up',line:[165,153,158,145,137,142,124],gap:'Grammar',gapScore:82,heat:[['Reading',88],['Grammar',82],['Vocabulary',83],['Listening',89]],title:{en:'Class 5A completion · Jan–Jul',zh:'5A 班完成率 · 1月至7月'}},
'5b':{label:{en:'Class 5B',zh:'5B 班'},completion:'80%',active:'29',attention:'1',change:'−2%',trend:'down',line:[145,151,146,156,151,165,171],gap:'Vocabulary',gapScore:65,heat:[['Reading',81],['Grammar',74],['Vocabulary',65],['Listening',82]],title:{en:'Class 5B completion · Jan–Jul',zh:'5B 班完成率 · 1月至7月'}},
g6:{label:{en:'Grade 6',zh:'六年級'},completion:'86%',active:'58',attention:'1',change:'+4%',trend:'up',line:[168,157,161,145,151,132,121],gap:'Grammar',gapScore:79,heat:[['Class 6A',91,85,87,92],['Class 6B',85,73,82,86]],title:{en:'Grade 6 completion · Jan–Jul',zh:'六年級完成率 · 1月至7月'}},
'6a':{label:{en:'Class 6A',zh:'6A 班'},completion:'89%',active:'29',attention:'0',change:'+5%',trend:'up',line:[171,159,164,146,151,128,113],gap:'Grammar',gapScore:85,heat:[['Reading',91],['Grammar',85],['Vocabulary',87],['Listening',92]],title:{en:'Class 6A completion · Jan–Jul',zh:'6A 班完成率 · 1月至7月'}},
'6b':{label:{en:'Class 6B',zh:'6B 班'},completion:'83%',active:'29',attention:'1',change:'−1%',trend:'mixed',line:[149,154,147,158,150,161,156],gap:'Grammar',gapScore:73,heat:[['Reading',85],['Grammar',73],['Vocabulary',82],['Listening',86]],title:{en:'Class 6B completion · Jan–Jul',zh:'6B 班完成率 · 1月至7月'}}
};
function heatClass(v){if(v>=88)return 'heat-excellent';if(v>=82)return 'heat-good';if(v>=74)return 'heat-mid';if(v>=65)return 'heat-low';return 'heat-critical'}

function localizeMetricLabel(label){
  if(currentLang!=='zh')return label;
  const m=String(label).match(/^Class\s+(\d[A-Z])$/);if(m)return m[1]+' 班';
  const g=String(label).match(/^Grade\s+(\d)$/);if(g)return '一二三四五六'[Number(g[1])-1]+'年級';
  return ({Reading:'閱讀',Grammar:'文法',Vocabulary:'詞彙',Vocab:'詞彙',Listening:'聆聽'})[label]||label;
}
function renderHeat(s,key){const el=document.getElementById('heatTable');if(!el)return;const classScope=!key.startsWith('g')&&key!=='school';if(classScope){el.style.gridTemplateColumns='90px 1fr';el.innerHTML='<div class="head"></div><div class="head">'+(currentLang==='zh'?'掌握度':'Mastery')+'</div>'+s.heat.map(r=>`<div class="rowhead">${localizeMetricLabel(r[0])}</div><div class="${heatClass(r[1])}">${r[1]}</div>`).join('')}else{el.style.gridTemplateColumns='90px repeat(4,1fr)';const hdr=['',currentLang==='zh'?'閱讀':'Reading',currentLang==='zh'?'文法':'Grammar',currentLang==='zh'?'詞彙':'Vocabulary',currentLang==='zh'?'聆聽':'Listening'];el.innerHTML=hdr.map((x,i)=>`<div class="head">${x}</div>`).join('')+s.heat.map(r=>`<div class="rowhead">${localizeMetricLabel(r[0])}</div>${r.slice(1).map(v=>`<div class="${heatClass(v)}">${v}</div>`).join('')}`).join('')}}
function renderBrief(s){const list=document.getElementById('briefList');if(!list)return;const l=s.label[currentLang],dir=s.trend;if(currentLang==='zh'){let items;if(dir==='down')items=[['趨勢需要支援',`${l} 的近期完成率正在回落，過去三個月未見穩定改善。`],['主要學習差距',`${s.gap} 是目前最明顯的薄弱範疇，掌握度約 ${s.gapScore}。`],['需要教師介入',`${s.attention} 名學生在自適應補強後仍未達掌握水平，建議安排針對性的面授補救。`]];else if(dir==='mixed')items=[['表現反覆',`${l} 整體水平相對穩定，但月度表現有明顯波動。`],['AI 已持續調整',`系統正增加 ${s.gap} 的個人化練習，以處理目前約 ${s.gapScore} 的掌握度。`],['教師重點',`${s.attention} 名學生仍需要支援；其餘學生由 EXAI 自動延續學習路徑。`]];else items=[['整體趨勢向好',`${l} 近期表現改善，即使期間有正常的月度波動。`],['仍可再提升',`${s.gap} 仍是相對較弱的範疇，掌握度約 ${s.gapScore}。`],['教師介入保持低位',`目前只有 ${s.attention} 名學生需要教師進一步介入，其餘補強由 EXAI 自動處理。`]];list.innerHTML=items.map((x,i)=>`<div class="brief-item trend-${dir}"><strong><span class="trend-symbol">${dir==='down'?'↓':dir==='mixed'?'↕':'↑'}</span>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}else{let items;if(dir==='down')items=[['Trend needs attention',`${l} is moving backwards recently, with no sustained recovery across the last three months.`],['Largest learning gap',`${s.gap} is the clearest weakness, currently around ${s.gapScore} mastery.`],['Human intervention',`${s.attention} students remain below mastery after adaptive remediation and should be addressed face-to-face.`]];else if(dir==='mixed')items=[['Performance is uneven',`${l} is broadly stable, but the month-to-month pattern is volatile rather than consistently improving.`],['AI is already adapting',`EXAI is increasing personalised ${s.gap} practice around the current ${s.gapScore} mastery level.`],['Teacher focus',`${s.attention} students still need attention; EXAI continues the learning path automatically for everyone else.`]];else items=[['Overall trend is positive',`${l} is improving despite normal month-to-month fluctuations.`],['Next opportunity',`${s.gap} remains the relatively weaker area at around ${s.gapScore} mastery.`],['Low intervention load',`Only ${s.attention} students currently require teacher intervention; EXAI continues remediation automatically for the rest.`]];list.innerHTML=items.map(x=>`<div class="brief-item trend-${dir}"><strong><span class="trend-symbol">${dir==='down'?'↓':dir==='mixed'?'↕':'↑'}</span>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}}
let currentScope='school';
function collapseGrades(except){document.querySelectorAll('#schoolTree .grade').forEach(g=>{const id=g.dataset.grade,open=id===except;const c=g.querySelector('.caret');if(c)c.textContent=open?'▼':'▶';document.querySelectorAll(`#schoolTree .class[data-parent="${id}"]`).forEach(x=>x.classList.toggle('is-hidden',!open))})}
function setScope(key,btn){currentScope=key;const s=scopes[key]||scopes.school;document.getElementById('metricCompletion').textContent=s.completion;document.getElementById('metricActive').textContent=s.active;document.getElementById('metricNeedsSupport').textContent=s.attention;const change=document.getElementById('metricChange');change.textContent=s.change;change.classList.toggle('trend-attention',s.trend==='down');document.getElementById('trendTitle').textContent=s.title[currentLang];const xs=[70,145,220,295,370,445,520],line=document.getElementById('scopeLine');line.setAttribute('points',xs.map((x,i)=>`${x},${s.line[i]}`).join(' '));line.setAttribute('class','chart-line '+(s.trend==='down'?'down':s.trend==='mixed'?'mixed':''));document.getElementById('scopeDots').innerHTML=xs.map((x,i)=>`<circle class="chart-dot ${s.trend==='down'?'down':s.trend==='mixed'?'mixed':''}" cx="${x}" cy="${s.line[i]}" r="5"/>`).join('');document.querySelectorAll('#schoolTree button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');renderHeat(s,key);renderBrief(s)}
document.querySelectorAll('#schoolTree .root').forEach(b=>b.addEventListener('click',()=>{collapseGrades(null);setScope('school',b)}));document.querySelectorAll('#schoolTree .grade').forEach(b=>b.addEventListener('click',()=>{collapseGrades(b.dataset.grade);setScope(b.dataset.scope,b)}));document.querySelectorAll('#schoolTree .class').forEach(b=>b.addEventListener('click',()=>setScope(b.dataset.scope,b)));
collapseGrades('g1');setScope('school',document.querySelector('#schoolTree .root'));
window.addEventListener('mousemove',e=>{if(innerWidth<900)return;const s=document.getElementById('heroStage');if(!s)return;const r=s.getBoundingClientRect(),dx=(e.clientX-(r.left+r.width/2))/r.width,dy=(e.clientY-(r.top+r.height/2))/r.height;s.querySelectorAll('.window').forEach((w,i)=>{const d=(i+1)*4;w.style.marginLeft=`${dx*d}px`;w.style.marginTop=`${dy*d}px`})});
setLanguage(currentLang);reset(mode);
