import fs from 'node:fs';import path from 'node:path';
import { marked } from '/Users/snapask/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/marked/lib/marked.esm.js';
const root=path.dirname(new URL(import.meta.url).pathname);
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rel=(from,to)=>path.relative(path.dirname(path.join(root,from)),path.join(root,to));
function docs(from,file){let text=marked.parse(fs.readFileSync(path.join(root,file),'utf8'));text=text.replace(/((?:href|src)=")([^"]+)(")/g,(all,a,u,b)=>{if(/^(?:[a-z]+:|#|\/)/i.test(u))return all;let resolved=path.resolve(root,path.dirname(file),u);if(resolved.endsWith('.md'))resolved=resolved.slice(0,-3)+'.html';return a+path.relative(path.dirname(path.join(root,from)),resolved)+b;}).replace(/<table>/g,'<div class="table-scroll"><table>').replace(/<\/table>/g,'</table></div>');text=text.replace(/<td>(#[0-9a-fA-F]{6})<\/td>/g,'<td><span class="colour-value"><i class="colour-dot" style="background:$1" aria-hidden="true"></i><code>$1</code></span></td>');text=text.replace(/<h1>.*?<\/h1>/s,'');return text.split(/(?=<h2>)/).filter(x=>x.trim()).map((s,i)=>`<article class="pin document ${i===0?'feature':''}" data-category="Guidelines"><div class="pin-body"><span class="tag">Guidelines · ${esc(path.basename(file,'.md'))}</span>${s}</div></article>`).join('');}
function image(from,file,title,category,desc=''){const url=esc(rel(from,file));return `<article class="pin" data-category="${esc(category)}"><button class="pin-media" data-src="${url}" data-title="${esc(title)}" aria-label="Preview ${esc(title)}"><img src="${url}" alt="${esc(title)}" loading="lazy" decoding="async"></button><div class="pin-body"><span class="tag">${esc(category)}</span><h2>${esc(title)}</h2>${desc?`<p>${esc(desc)}</p>`:''}<a href="${url}" download>Download image ↗</a></div></article>`;}
function build(file,title,subtitle,section,cards){const cats=[...new Set([...cards.matchAll(/data-category="([^"]+)"/g)].map(x=>x[1]))];const nav=[['index.html','UI guidelines','ui'],['character/index.html','Characters','character'],['asset/index.html','Scenes','asset'],['archive/index.html','Archive','archive']].map(([u,t,id])=>`<a href="${rel(file,u)}" class="${id===section?'active':''}" ${id===section?'aria-current="page"':''}>${t}</a>`).join('');fs.writeFileSync(path.join(root,file),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Kokomonster</title><link rel="stylesheet" href="${rel(file,'library.css')}"><script defer src="${rel(file,'library.js')}"></script></head><body><aside class="sidebar"><a class="brand" href="${rel(file,'index.html')}"><img class="official-logo" src="${rel(file,'official-logo.png')}" alt="Kokomonster"></a><span class="side-label">DESIGN LIBRARY</span><nav aria-label="Library sections">${nav}</nav></aside><div class="app"><div class="topbar"><label class="search"><span aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg></span><input id="search" type="search" placeholder="Search this collection" aria-label="Search this collection"></label></div><main><header><span class="eyebrow">KOKOMONSTER / ${esc(section.toUpperCase())}</span><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></header><div class="filters" aria-label="Filter collection">${['All',...cats].map((c,i)=>`<button data-filter="${esc(c)}" class="${i===0?'active':''}" aria-pressed="${i===0}">${esc(c)}</button>`).join('')}</div><p id="count" class="count"></p><div class="masonry">${cards}</div><p class="empty" hidden>No matching items. Try another search or filter.</p></main></div><dialog aria-label="Image preview"><div class="modal-head"><h2></h2><a download>Download original ↗</a><button aria-label="Close preview">×</button></div><img class="preview-image" alt=""></dialog></body></html>`);}
const jobs=JSON.parse(fs.readFileSync(path.join(root,'asset/japanese-20-style-A/manifest.json'),'utf8'));
const sceneCards=from=>jobs.map(j=>image(from,'asset/japanese-20-style-A/'+j.file,j.title,'Style A',j.placement+' · '+j.cast)).join('');
const titles={ui:['Interface foundations','A shared visual language for every Kokomonster experience.'],character:['Meet the characters','One cast, four drawing styles. Keep identity consistent across every story.'],asset:['A world of scenes','Japanese places, everyday moments and stories ready for page composition.'],archive:['The reference collection','Original extractions, turntable frames and early explorations, preserved for reference.']};
for(const file of walk(root).filter(x=>x.endsWith('.md'))){const local=path.relative(root,file);const out=local.replace(/\.md$/,'.html');const section=local.startsWith('archive/')?'archive':local.startsWith('character/')?'character':local.startsWith('asset/')?'asset':'ui';const title=fs.readFileSync(file,'utf8').match(/^# (.+)/m)?.[1]||path.basename(file,'.md');build(out,title,'Guidelines and reference notes from the Kokomonster design library.',section,docs(out,local));}
let out='index.html';build(out,...titles.ui,'ui',docs(out,'UI-GUIDELINES.md')+image(out,'asset/japanese-20-style-A/KM-SCN-A-01-bookshop.png','Flat Adventure in context','Inspiration','The selected illustration style for the landing page.'));
out='character/index.html';let cards=['A','B','C','D'].map((c,i)=>image(out,`character/style-system-v1/${c}-characters-v1.png`,['A — Flat Adventure','B — Colour Doodle','C — Compact Outline','D — 365 Companion'][i],'Style sheets')).join('');cards+=docs(out,'character/README.md')+docs(out,'character/style-system-v1/GUIDE.md');
for(const f of walk(path.join(root,'character/rotation-sources')).filter(f=>f.endsWith('.json'))){const name=path.basename(f,'.json');const board='archive/exploration/'+name+'-all-frames.jpg';if(fs.existsSync(path.join(root,board)))cards+=image(out,board,name.replace('360','')+' · turntable','Rotation reference', 'Original character construction')+`<article class="pin" data-category="Rotation reference"><div class="pin-body"><span class="tag">Lottie source</span><h2>${esc(name)}</h2><a href="${rel(out,path.relative(root,f))}" download>Download rotation JSON ↗</a></div></article>`;}
build(out,...titles.character,'character',cards);
out='asset/index.html';cards=sceneCards(out)+docs(out,'asset/README.md');for(const dir of ['asset/landing-page-style-A','asset/style-comparisons'])for(const f of walk(path.join(root,dir)).filter(f=>f.endsWith('.png')))cards+=image(out,path.relative(root,f),path.basename(f,'.png'),'Earlier studies');for(const f of ['asset/japanese-festival-collage/KM-CAM-A-japanese-festival-v1.png','asset/japanese-festival-collage/exact-layered/KM-CAM-A-japanese-festival-exact-layered-preview.png'])if(fs.existsSync(path.join(root,f)))cards+=image(out,f,f.includes('exact-layered')?'Japanese festival collage · exact layered master':'Japanese festival collage · flattened concept','Campaign concepts',f.includes('exact-layered')?'Pixel-identical SVG master with independently selectable item layers':'Original visual direction mockup');build(out,...titles.asset,'asset',cards);
out='asset/japanese-20-style-A/index.html';build(out,'20 Japanese moments','Style A scenes with costumes, props and suggested page placements.','asset',sceneCards(out)+docs(out,'asset/japanese-20-style-A/README.md'));
out='archive/index.html';cards=docs(out,'archive/README.md');for(const f of walk(path.join(root,'archive')).filter(f=>/\.(png|jpg|jpeg)$/i.test(f))){const local=path.relative(root,f);const cat=local.includes('extracted-library/characters')?'Extracted cutouts':local.includes('rotation-frames')?'Rotation frames':local.includes('game-style-trials')?'Style trials':'Source references';cards+=image(out,local,path.basename(f).replace(/\.(png|jpg|jpeg)$/i,'').replace(/[-_]/g,' '),cat);}build(out,...titles.archive,'archive',cards);
console.log('Built all HTML pages with the shared masonry library layout.');
